name: inherit called
on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  print-secret-ooh:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo org secret secrets.TESTING: ${{ secrets.TESTING }}
