# This is a basic workflow to help you get started with Actions

name: inherit calling

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    uses: ./.github/workflows-lab/inherit-called.yml
    secrets: inherit
